// deno-lint-ignore-file no-explicit-any
//this file is generated by generate_ast.ts
import { Token } from "./token.ts";
import { Expr } from "./expr.ts"

export abstract class Stmt {
    abstract accept(visitor: Visitor<any>):any;
}

export interface Visitor<R> {
    visitExpressionStmt(stmt:Expression): R;
    visitPrintStmt(stmt:Print): R;
    visitVarStmt(stmt:Var): R;
}

export class Expression extends Stmt {
    readonly expression:Expr;
    constructor(expression:Expr) {
        super();
        this.expression = expression;
    }

    accept(visitor:Visitor<any>): any {
        return visitor.visitExpressionStmt(this);
    }
}
export class Print extends Stmt {
    readonly expression:Expr;
    constructor(expression:Expr) {
        super();
        this.expression = expression;
    }

    accept(visitor:Visitor<any>): any {
        return visitor.visitPrintStmt(this);
    }

}
export class Var extends Stmt {
    readonly name:Token;
    readonly initializer:Expr;
    constructor(name:Token, initializer:Expr) {
        super();
        this.name = name;
        this.initializer = initializer;
    }

    accept(visitor:Visitor<any>): any {
        return visitor.visitVarStmt(this);
    }

}

